Insert into CURR_EXCHANGE(ID, FROM_CURR, TO_CURR, VALUE,CONVERTION_DATE)
values(1,'USD','INR',65,null);

Insert into CURR_EXCHANGE(ID, FROM_CURR, TO_CURR, VALUE,CONVERTION_DATE)
values(2,'SGD','INR',45.5,null);